sqlite3:
  :adapter: sqlite3
  :dbfile: vendor/plugins/granular_permissions/spec/db/granular_permissions_plugin.sqlite3.db
  :database: vendor/plugins/granular_permissions/spec/db/granular_permissions_plugin.sqlite3.db
